comment: "自动关闭：未按照模板格式提交"
issueConfigs:
  - content:
      # bug report
      - "问题描述"
      - "复现步骤"
      - "截图"
      - "环境信息"
      - "日志"
      - "安卓版本"
      - "哔哩漫游版本"
      - "哔哩哔哩版本和版本号"
      - "使用的框架和版本"
  - content:
      # feature request
      - "原因"
      - "功能简述"
      - "功能逻辑"
caseInsensitive: false
label: "spam"
